### ISSUE TITLE
Navigation menu not displayed

### ISSUE THREAD

**Issue by ddelkhosh** [google/typedoc-neo-theme#58]
![error](https://user-images.githubusercontent.com/66408731/89779402-8e808080-db0f-11ea-8e9f-4f4a933d19dc.png)
after creating documentation, search.js resource will not be loaded and navigation menu is invisible

"typedoc": "0.18.0"
"typedoc-neo-theme": "1.0.9"

**Comment by Fleker** [comment]
There is some ongoing work to support the new `search.json` format, as `search.js` has been removed from `typedoc` (see https://github.com/TypeStrong/typedoc/issues/1247).

Once this fix is released, you will be able to use it alongside typedoc v0.17.x. I have not investigated compatibility with v0.18.x.

**Comment by ddelkhosh** [comment]
> There is some ongoing work to support the new `search.json` format, as `search.js` has been removed from `typedoc` (see [TypeStrong/typedoc#1247](https://github.com/TypeStrong/typedoc/issues/1247)).
> 
> Once this fix is released, you will be able to use it alongside typedoc v0.17.x. I have not investigated compatibility with v0.18.x.

With Typedoc 0.17.3 Search worked but still navigation menu is not displayed!

**Comment by Fleker** [comment]
Are there any console errors, or is the HTML itself not being generated correctly?

**Comment by ddelkhosh** [comment]
> Are there any console errors, or is the HTML itself not being generated correctly?

There are no console errors, HTML generated  without any Error but Navigation Menu is not displayed. 
I test in empty Angular Project and Problem still exists.
"typedoc": "0.17.3"
"typedoc-neo-theme": "1.0.9"

**Comment by Fleker** [comment]
I'll take a look.

**Comment by coderew** [comment]
I have meet the same problem:
` "typedoc": "^0.18.0",
   "typedoc-neo-theme": "^1.0.9",
   "typescript": "^3.9.7"
`
I find the generated html has the style `display: none`

**Comment by Fleker** [comment]
Thanks. A fix is in development now.

**Comment by Fleker** [comment]
v1.0.10 is released.
